adding firewall_device module
linode/ansible_linode pull request #143
Opened 2022-04-13 19:54 UTC by jriddle-linode

2022-04-14 13:48 UTC, LBGarber requested changes
Looks good assuming tests are passing! Just a few small changes.

You can run `make gendocs` to generate the `DOCUMENTATION` field and the corresponding docs RST.

2022-04-14 13:48 UTC, LBGarber commented on plugins/modules/firewall_device.py
> +    ),
It might be a bit more intuitive to name these `device_id` and `device_type` 👍

2022-04-14 13:48 UTC, LBGarber commented on plugins/modules/firewall_device.py
> +    def _create_node(self) -> linode_api4.FirewallDevice:
Should this be `_create_device`?

2022-04-14 16:29 UTC, jriddle-linode commented
docs updated and mentioned requests changed, i went back and forth on device_id vs firewall_device_id like 10 times

2022-04-14 16:34 UTC, l8gravely commented
>>>>> "Jacob" == Jacob Riddle ***@***.***> writes:

Jacob> docs updated and mentioned requests changed, i went back and forth on device_id vs
Jacob> firewall_device_id like 10 times

fw_dev_id?  Maybe something shorter is ok?  Or fw_device_id?

Yeah, I'm just bikeshedding here...

John

2022-04-14 17:03 UTC, LBGarber commented
I'm still thinking on this myself. The Linode API does differentiate device/assignment IDs from entity IDs so it might be best to change the naming to prevent ambiguity. I wonder if simple `id` and `type` fields would be sufficient :thinking: 

Here's what we do in the Terraform provider: https://registry.terraform.io/providers/linode/linode/latest/docs/resources/firewall_device#argument-reference

API request: https://www.linode.com/docs/api/networking/#firewall-device-create__request-body-schema

2022-04-15 14:11 UTC, LBGarber requested changes
Looks good! One small thing and we should be good to go 🙂

2022-04-15 14:11 UTC, LBGarber commented on plugins/modules/firewall_device.py
> +                if device.id == entity_id:
```suggestion
            entity_id = params['entity_id']
            entity_type = params['entity_type']

            firewall = linode_api4.Firewall(self.client, firewall_id)
            for device in firewall.devices:
                if device.entity.id == entity_id and device.entity.type == entity_type:
```

2022-04-15 14:11 UTC, LBGarber commented on tests/integration/targets/firewall_device/tasks/main.yaml
> +          - fw_device.changed
We might want to duplicate this test and assert `not fw_device.changed` to make sure we properly retrieve existing devices.

2022-04-15 14:30 UTC, LBGarber approved these changes

2022-04-15 14:31 UTC, merged