SSH Key List Module
linode/ansible_linode pull request #273
Opened 2023-01-24 22:30 UTC by zliang-akamai

2023-01-24 23:30 UTC, zliang-akamai commented
Auto generated doc has the white space again? Will fix...

2023-01-25 16:46 UTC, jriddle-linode approved these changes

2023-01-26 16:40 UTC, lgarber-akamai commented
/acctest sha=785324ae31b3db1625b1a11e55352ce8439a376f tests=ssh_key_list

2023-01-26 16:45 UTC, lgarber-akamai requested changes
Great work! Just a few small things

2023-01-26 16:45 UTC, lgarber-akamai commented on tests/integration/targets/ssh_key_info/tasks/main.yaml
> -            api_token: '{{ api_token }}'
Unfortunately we'll have to keep these in for now since `ansible-test` does not natively pass-through shell environment variables.

2023-01-26 16:45 UTC, lgarber-akamai commented on docs/modules/ssh_key_list.md
> +# ssh_key_list
Could you re-run `make gendocs` to get the docs validation workflow passing again? The whitespace issue will be fixed once we bump and update for `ansible-specdoc`.

2023-01-26 16:57 UTC, lgarber-akamai commented on tests/integration/targets/ssh_key_info/tasks/main.yaml
> -            api_token: '{{ api_token }}'
Actually, I did a bit more digging and we can at least simplify this by specifying `environment` at the bottom of a block:

```yaml
- name: my_tests
  block:
        ......
  always:
    - ignore_errors: yes
      block:
          .........

  environment:
    LINODE_UA_PREFIX: '{{ ua_prefix }}'
    LINODE_API_TOKEN: '{{ api_token }}'
```

2023-01-26 22:53 UTC, zliang-akamai commented
/acctest sha=785324ae31b3db1625b1a11e55352ce8439a376f tests=ssh_key_list

2023-01-27 17:31 UTC, lgarber-akamai approved these changes
Great work!

2023-01-27 17:32 UTC, lgarber-akamai commented
/acctest sha=b90ea8f3378aaac3cb87b239f608b69745545eb6 tests=ssh_key_list

2023-01-27 17:34 UTC, zliang-akamai commented on docs/modules/ssh_key.md
>          {}
That's actually a valid sample response by the DELETE method...
https://www.linode.com/docs/api/profile/#ssh-key-delete__response-samples

2023-01-27 17:37 UTC, merged

2023-01-27 17:38 UTC, lgarber-akamai commented on docs/modules/ssh_key.md
>          {}
Oh interesting, wonder if that's worth keeping considering that applies to all DELETE endpoints. I'm definitely open to discussion about it 🤔