Add `instance_type_list` module
linode/ansible_linode pull request #300
Opened 2023-02-23 18:38 UTC by ezilber-akamai

## 📝 Description

Add `instance_type_list` module

2023-02-23 18:47 UTC, ezilber-akamai commented
/acctest tests=instance_type_list sha=7f66a8f4df672492f55863c0c45cbaf43b8a9245

2023-02-23 20:51 UTC, zliang-akamai approved these changes

2023-02-24 16:24 UTC, lgarber-akamai requested changes
Great work! Just a few small typo corrections

2023-02-24 16:24 UTC, lgarber-akamai commented on plugins/modules/instance_type_list.py
> +        instanceTypes=SpecReturnValue(
Looks like this should be `instance_types`

2023-02-24 16:24 UTC, lgarber-akamai commented on plugins/module_utils/doc_fragments/instance_type_list.py
> +result_images_samples = ['''[
Quick correction just for consistency:
`result_images_samples` -> `result_instance_types_samples`

2023-02-24 19:22 UTC, lgarber-akamai approved these changes

2023-02-24 19:23 UTC, merged