Added `nodebalancer_list`, `object_cluster_list`, and `user_list` modules
linode/ansible_linode pull request #313
Opened 2023-02-28 21:13 UTC by ezilber-akamai

## 📝 Description

Added `nodebalancer_list`, `object_cluster_list`, and `user_list` modules

## ✔️ How to Test

`make TEST_ARGS="-v nodebalancer_list" test`
`make TEST_ARGS="-v object_cluster_list" test`
`make TEST_ARGS="-v user_list" test`

2023-03-01 14:25 UTC, ezilber-akamai commented
/acctest tests=nodebalancer_list,object_cluster_list,user_list sha=1ffe51731be96ee46415ad72bc9713a07c0a3d35

2023-03-02 19:11 UTC, lgarber-akamai requested changes

2023-03-02 19:11 UTC, lgarber-akamai commented on plugins/modules/object_cluster_list.py
> +        object_clusters=SpecReturnValue(
object_clusters -> clusters

2023-03-02 19:19 UTC, lgarber-akamai approved these changes

2023-03-02 19:19 UTC, zliang-akamai approved these changes

2023-03-02 19:21 UTC, ezilber-akamai commented
/acctest tests=nodebalancer_list,object_cluster_list,user_list sha=f61a2f01af65ad83e1128b090984537796d7e2ad

2023-03-02 19:22 UTC, merged