Fix typo in documentation of `linode.cloud.instance_list`
linode/ansible_linode pull request #335
Opened 2023-04-12 15:12 UTC by grzegorzk

## 📝 Description

**What does this PR do and why is this change necessary?**

Minor fix to documentation

## ✔️ How to Test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run the relevant unit/integration tests?**

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

2023-04-14 17:09 UTC, lgarber-akamai requested changes
@grzegorzk Hello, thanks for the pull request!

Our documentation is generated directly from the embedded module spec. Could you make the change in the corresponding doc fragment and run `make gendocs` to re-generate the documentation? 

See: https://github.com/linode/ansible_linode/blob/dev/plugins/module_utils/doc_fragments/instance_list.py#L8

One more thing: It looks like we have this same typo in the documentation for a good portion of our list modules. Would you mind also updating the other occurrences of this issue? No worries if you'd like to keep this PR scoped to the `instance_list` module 🙂

2023-04-14 23:11 UTC, grzegorzk commented
Hi @lgarber-akamai, done following your hints, thanks!

2023-04-17 17:27 UTC, lgarber-akamai approved these changes
Looks good! Thanks for the contribution

2023-04-18 16:14 UTC, zliang-akamai approved these changes

2023-04-18 16:14 UTC, merged