Fix body_json parsing of api_request module
linode/ansible_linode pull request #342
Opened 2023-04-27 12:43 UTC by zliang-akamai

## 📝 Description

closes #334

Translate `body_json` parameter to json to fix an issue that trouble the users.

## ✔️ How to Test

`make TEST_ARGS="-v api_request_extra" test`
`make TEST_ARGS="-v api_request_basic" test`

2023-04-27 14:53 UTC, lgarber-akamai commented
/acctest tests=api_request_extra sha=9838372270f5a8af29a759bfbe4687065f488f6b

2023-04-27 15:15 UTC, lgarber-akamai requested changes
Great work! This solution is really clever.
Just a small refactor and we should be good to go 👍

2023-04-27 15:54 UTC, zliang-akamai commented on plugins/modules/api_request.py
> +
Applied. Thank you for the suggestion!

2023-04-27 16:01 UTC, lgarber-akamai approved these changes
Nice work!

2023-04-27 16:46 UTC, zliang-akamai commented
/acctest tests=api_request_extra sha=62158be127c60fdd86de588abcdf1caf060b4297

2023-04-27 16:48 UTC, zliang-akamai commented
/acctest tests=api_request_extra sha=62158be127c60fdd86de588abcdf1caf060b4297

2023-04-27 17:03 UTC, zliang-akamai commented
/acctest tests=api_request_extra sha=c9beefb17ea551a72ce0975da0466acadf5652bc

2023-04-27 17:25 UTC, zliang-akamai commented
/acctest tests=api_request_extra sha=c9beefb17ea551a72ce0975da0466acadf5652bc

2023-04-27 17:28 UTC, zliang-akamai commented
/acctest tests=api_request_extra sha=0560d90f86ff96e44a0919c504dfa0bcfa4ba8a2

2023-04-27 17:37 UTC, zliang-akamai commented
/acctest tests=api_request_extra sha=cb460c0495e52ec6d0ebfec3f1281d9e9506e44e

2023-04-27 18:20 UTC, zliang-akamai commented
/acctest tests=api_request_extra sha=cb460c0495e52ec6d0ebfec3f1281d9e9506e44e

2023-04-28 17:27 UTC, yec-akamai approved these changes

2023-04-28 18:52 UTC, merged